version: '2.1'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
    - 2181:2181
    volumes:
    - "~/Documents/docker/zookeeper/zoo1/data:/data"
    - "~/Documents/docker/zookeeper/zoo1/datalog:/datalog"

  kafka1:
    image: wurstmeister/kafka:2.11-2.0.1
    restart: always
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.31.132.5:9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
    volumes:
    - ~/Documents/docker/kafka/kafka1/logs:/kafka
    depends_on:
      - zoo1

  flink-jobmanager:
    image: flink:1.7.1-scala_2.11-alpine
    ports:
      - "8081:8081"
    expose:
      - "6123"
    command: jobmanager
    depends_on:
      - kafka1
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager

  flink-taskmanager:
    image: flink:1.7.1-scala_2.11-alpine
    expose:
      - "6121"
      - "6122"
    depends_on:
      - flink-jobmanager
    links:
      - flink-jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager